config/routes.rb
Betastore::Application.routes.draw do 
  devise_for :users
  resources :users
  resources :products
  resources :subscriptions
  
  post '/products/:product_id/add_to_cart' => 'carts#update', as: 'add_to_cart'
  get '/cart' => 'carts#show', as: 'cart'

  put '/orders' => 'orders#update', as: 'order'

  get '/completed' => 'orders#show', as: 'completed'
  #SCF Do I need this?
  #put '/completed' => 'orders#show', as: 'completed'

  get '/checkout'   => 'orders#new', as: 'neworder'
  post '/checkout'  => 'orders#create'

  namespace :admin do
    resources :products
    #SCFbinding.pry
    resources :users
    resources :customers
    get '/login' => 'logins#new', as: 'logins'
    post '/login' => 'logins#create'
  end
  root :to => 'products#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  belongs_to :credit_card
  belongs_to :shipping_address
  has_many :line_items
  has_many :products, :through => :line_items

  accepts_nested_attributes_for :line_items, :credit_card, :shipping_address

  def self.from_cart(cart)
    order = new
    cart.each do |product_id, quantity|
      order.line_items.build(
        product: Product.find(product_id),
        quantity: quantity
        )
    end
    order
  end

  def total
    line_items.to_a.sum(&:total_price)
    # SCF is equivalent to:
    #line_items.to_a.sum{ |i| i.total_price }
    # sum = 0
    # for line_item in line_items do
    #   sum += line_item.total_price
    # end
    # sum
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @order = Order.from_cart(session[:cart])
    @order.build_credit_card
    @order.build_shipping_address
  end
  
  def update
    #SCF
    cart_params = params[:order][:line_items_attributes]
    logger.debug "cart_params: #{cart_params.values.inspect}"
    logger.debug "cart: #{session[:cart].inspect}"
    
    new_cart = {}
    
    for item in cart_params.values
      #binding.pry
      #SCFnew_cart = session[:cart][""].select {|k| k["quantity"] == 2}
      #new_cart = session[:cart].each{ |product_id, quantity| "#{"product_id" => product_id} #{"quantity" => quantity}" }
      new_cart[item["product_id"]] = item["quantity"].to_i
      #new_cart = session[:cart].each{ |product_id, quantity| {item[product_id] => item[quantity]} }
      ##session[:cart].merge!(item) { |product_id, v1, quantity| v1 }
      #SCF
      session[:cart] = new_cart
    end

    logger.debug "new_cart: #{new_cart.inspect}"
    #session[:cart] = {"1" => 3, "155" => 0}
    redirect_to cart_path, notice: 'Your cart was updated'
  end

  def show
    @order = Order.from_cart(session[:cart])
  end

end

app/views/orders/new.html.erb
<h1>Checkout</h1>

<%= form_for @order, url: checkout_path do |f| %>
<table class="table">
  <tr>
    <th>Product</th>
    <th>Quantity</th>
    <th>Base Price</th>
    <th>Total Price</th>
  </tr>
  
   <%= f.fields_for :line_items do |li| %>
      <% line_item = li.object %>
      <%= li.hidden_field :product_id %>
      <%=li.hidden_field :quantity %>
    <tr>
      <td><%= line_item.product.name %></td>
      <td><%= line_item.quantity %></td>
      <td><%= number_to_currency line_item.total_price %></td> 
    </tr>
    <% end %>
  
  
  <tr> 
    <td colspan="3">
    <td><%= number_to_currency @order.total %></td>
    </td>
  </tr> 
  
  </table>


<%= link_to "Edit Order", cart_path, class: 'btn btn-primary' %>

<div class="row">
  <%= f.fields_for :credit_card do |cc| %>
  <div class="col-md-6">
  <h2>Credit Card Information</h2>

  <div class="form-group">
    <%= cc.label :number, class: "col-sm-2 control-label "%>
    <div class="col-sm-10">
      <%= cc.text_field :number, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= cc.label :exp_date, class: "col-sm-2 control-label "%>
    <div class="col-sm-10">
      <%= cc.text_field :exp_date, class: 'form-control' %>
    </div>
  </div>
  <% end %>
  <%= f.fields_for :shipping_address do |sa| %>
    <div class="col-md-6">
      <h2>Shipping Information</h2>
        
        <div class="form-group">
          <%= sa.label :street, class: "col-sm-2 control-label "%>
          <div class="col-sm-10">
            <%= sa.text_field :street, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= sa.label :city, class: "col-sm-2 control-label "%>
          <div class="col-sm-10">
            <%= sa.text_field :city, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= sa.label :state, class: "col-sm-2 control-label "%>
          <div class="col-sm-10">
            <%= sa.text_field :state, class: 'form-control' %>
          </div>
        </div>



        <div class="form-group">
          <%= sa.label :zip, class: "col-sm-2 control-label "%>
          <div class="col-sm-10">
            <%= sa.text_field :zip, class: 'form-control' %>
          </div>
        </div>

        <%= link_to "Submit Order", completed_path, class: 'btn btn-success' %>

      </div> 
  <% end %>
  </div>

<% end %>

app/views/orders/show.html.erb
<h1>Completed Order</h1>

<table class="table">
  <tr>
    <th>Product</th>
    <th>Quantity</th>
    <th>Base Price</th>
    <th>Total Price</th>
  </tr>
  <%= form_for @order, url: order_path, html: { method: 'put' } do |f| %>
   <%= f.fields_for :line_items do |li| %>
      <% line_item = li.object %>
      <%= li.hidden_field :product_id %>
    <tr>
      <td><%= line_item.product.name %></td>
      <td><%= line_item.quantity %></td>
      <td><%= number_to_currency line_item.total_price %></td> 
    </tr>
    <% end %>
  
  
  <tr> 
    <td colspan="3">
    <%= link_to "Print Receipt", completed_path, class: 'btn btn-primary' %>
     </td>
    <td><%= number_to_currency @order.total %></td>
  </tr> 
  <% end %>
  </table>