config/routes.rb
Betastore::Application.routes.draw do 
  devise_for :users
  resources :users
  resources :products
  resources :subscriptions
  
  post '/products/:product_id/add_to_cart' => 'carts#update', as: 'add_to_cart'
  get '/cart' => 'carts#show', as: 'cart'

  put '/orders' => 'orders#update', as: 'order'

  get '/completed' => 'orders#show', as: 'completed'
  #SCF Do I need this?
  #put '/completed' => 'orders#show', as: 'completed'

  get '/checkout'   => 'orders#new', as: 'neworder'
  post '/checkout'  => 'orders#create'

  namespace :admin do
    resources :products
    #SCFbinding.pry
    resources :users
    resources :customers
    get '/login' => 'logins#new', as: 'logins'
    post '/login' => 'logins#create'
  end
  root :to => 'products#index'

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_action :require_login

  def index
    if logged_in?
      @products = Product.order('name')
    else
      redirect_to admin_login_path, alert: 'Please log in to continue'
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product), notice: "Product #{@product.id} was created.  "
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    #SCF WORKS!
    if @product.update(product_params)
      redirect_to admin_product_path(@product), notice: "Product #{@product.id} was updated.  "
    else
      render 'edit'
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    redirect_to admin_products_path, :flash => { :success => "Product deleted." }
  end


  private
  def product_params
    params.require(:product).permit(:name, :price)
  end

  def logged_in?
    session[:user_id].present?
  end

  def require_login
    unless logged_in?
      redirect_to admin_logins_path, danger: 'Please log in to continue'
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order('name')
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/views/products/index.html.erb
<h1>Products</h1>

<div class="row">
    <% for product in @products %>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <%= image_tag product.image_url, class: "image-responsive" %>
            <div class="caption">
                <h3><%= link_to product.name, product_path(product) %></h3>
                <h3><%= number_to_currency product.price %>
                <p><h5><%= product.description %></h5></p>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
  <p>
  <%= image_tag @product.image_url, alt: @product.name, class: 'img-responsive' %>
  </p>
<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Price</th>
    <th>Description</th>
    <th>Created At</th>
  </tr>
    <tr>
      <td><%= @product.id %></td>
      <td><%= @product.name %></td>
      <td><%= @product.price %></td>
      <td><%= @product.description %></td>
      <td><%= @product.created_at %></td>
    </tr>
  </table>
  <p><%= link_to "Add to Cart", add_to_cart_path(@product.id), class:'btn btn btn-success', method: 'post' %></p>  

  <p>
  <%= link_to "Back to Product List",products_path %>
  </p>