config/routes.rb
Betastore::Application.routes.draw do 
  devise_for :users
  resources :users
  resources :products
  resources :subscriptions
  
  post '/products/:product_id/add_to_cart' => 'carts#update', as: 'add_to_cart'
  get '/cart' => 'carts#show', as: 'cart'

  put '/orders' => 'orders#update', as: 'order'

  get '/completed' => 'orders#show', as: 'completed'
  #SCF Do I need this?
  #put '/completed' => 'orders#show', as: 'completed'

  get '/checkout'   => 'orders#new', as: 'neworder'
  post '/checkout'  => 'orders#create'

  namespace :admin do
    resources :products
    #SCFbinding.pry
    resources :users
    resources :customers
    get '/login' => 'logins#new', as: 'logins'
    post '/login' => 'logins#create'
  end
  root :to => 'products#index'

end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Betastore", products_path %>
    </div>
    <ul class="nav navbar-nav">
      <li>
        <%= link_to "Products", products_path %>
      </li>
      <li>
        <%= link_to "Admin", admin_products_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Betastore</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <div class="container">
      <%= render "layouts/nav" %>
      <% if flash[:notice].present? %>
        <div class="row">
          <div class="alert alert-success"><%= flash[:notice] %></div>
        </div>
      <% end %>

      <% if flash[:danger].present? %>
        <div class="alert alert-danger"><%= flash[:notice] %>
        </div>
      <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Betastore</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <% if flash[:notice].present? %>
        <div class="row">
          <div class="alert alert-success"><%= flash[:notice] %></div>
        </div>
      <% end %>
      <% if flash[:danger].present? %>
        <div class="row">
          <div class="alert alert-danger"><%= flash[:danger] %></div>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>